### ISSUE TITLE
Start-Order: Opening Uart results in Midi-Reset

### ISSUE THREAD

**Issue by schlenkibus** [nonlinear-labs-dev/C16-eval#4]
steps to reproduce:
- start `erp-readout` or `amidi -d`
- start `test_serial`

observed behaviour:
erp-readout exits with code 0, and amidi -d also exits with return code 0

(in the rust project reading from the already open midi-fd fails with error-code ENODEV (no device))

Maybe we should test if the behavior also appears on the RPI with direct Serial Interface instead of USB?

**Comment by KlausStrohhaecker** [comment]
The issue comes from Serial over USB (FTDI chip) which touches the modem lines during file opening of the serial port. Modem lines are then are set properly in the port setup but at that time it's to late as one of the modem lines is attached to the LPC's reset pin.
Fix: Remove jumpers on eval board for the modem control lines (center pair of jumpers) when using serial over USB.
